version: "3.8"

services:
  www:
    build:
      context: ./bin/php
    container_name: "${PROJECT_NAME}-www"
    restart: "always"
    ports:
      - "${WWW_UNSECURE_PORT}:80"
      - "${WWW_SECURE_PORT}:443"
    links:
      - database
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${APACHE_LOG_DIR}:/var/log/apache2

  database:
    build:
      context: "./bin/mysql"
    container_name: "${PROJECT_NAME}-database"
    restart: "always"
    platform: linux/x86_64
    ports:
      - "127.0.0.1:${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_LOG_DIR}:/var/log/mysql
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql

  phpmyadmin:
    container_name: "${PROJECT_NAME}-pma"
    restart: "always"
    image: phpmyadmin/phpmyadmin
    links:
      - database
    ports:
      - "${PMA_PORT}:80"
    environment:
      UPLOAD_LIMIT: 1G
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /sessions
      - ${PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
